name: 'Authorize Org'
inputs:
  encoded_private_key_content:
    required: true
  encode_raw_key:
    required: true
  encode_iv:
    required: true
  client_id:
    required: true
  username:
    required: true
  alias:
    required: true
  is-devhub:
    required: false
    default: false
  is-scratch:
    required: false
    default: false
  set-default:
    required: false
    default: false
runs:
  using: 'composite'
  steps:
    - name: define env in this action
      id: define-env
      run: |
        private_key_dir=${RUNNER_TEMP}/${{ inputs.alias }}
        private_key_file_encoded=${private_key_dir}/server.pem.enc
        private_key_file=${private_key_dir}/server.pem

        echo "private_key_dir=${private_key_dir}" >> $GITHUB_OUTPUT
        echo "private_key_file_encoded=${private_key_file_encoded}" >> $GITHUB_OUTPUT
        echo "private_key_file=${private_key_file}" >> $GITHUB_OUTPUT        
      shell: bash

    - name: generate private key from encoded private key
      run: |
        private_key_dir=${{ steps.define-env.outputs.private_key_dir }}
        private_key_file_encoded=${{ steps.define-env.outputs.private_key_file_encoded }}
        private_key_file=${{ steps.define-env.outputs.private_key_file }}

        mkdir -p ${private_key_dir}

        echo ${{ inputs.encoded_private_key_content }} | base64 -d > ${private_key_file_encoded}
        openssl enc -nosalt -aes-256-cbc -d -in ${private_key_file_encoded} -out ${private_key_file} -base64 -K ${{ inputs.encode_raw_key }} -iv ${{ inputs.encode_iv }}
      shell: bash

    - name: authorize org
      run: |
        private_key_file=${{ steps.define-env.outputs.private_key_file }}

        declare option_instance_url
        if ${{ inputs.is-scratch }} ; then
          option_instance_url="--instance-url https://test.salesforce.com"
        fi

        declare option_set_default
        if ${{ inputs.is-devhub }} && ${{ inputs.set-default }} ; then
          option_set_default="--set-default-dev-hub"
        elif ! ${{ inputs.is-devhub }} && ${{ inputs.set-default }} ; then
          option_set_default="--set-default"
        fi

        sf auth jwt grant --client-id ${{ inputs.client_id }} --jwt-key-file ${private_key_file} --username ${{ inputs.username }} ${option_instance_url} ${option_set_default} --alias ${{ inputs.alias }} --json
      shell: bash

    - name: confirm org list
      run: sf org list
      shell: bash
