name: 'Hello'
description: 'Say Hello'
inputs:
  who-to-greet:
    required: true
outputs:
  greet:
    value: ${{ steps.say-hello.outputs.greet }}
runs:
  using: 'composite'
  steps:
    - id: say-hello
      run: |
        declare greet="Hello ${{ inputs.who-to-greet }}."
        echo ${greet}
        echo "greet=${greet}" >> $GITHUB_OUTPUT
      shell: bash