name: CI workflow

on:
  workflow_dispatch:
    inputs:
      scratch_username:
        description: 'when input, connected to username for scratch'
        required: false
        type: string
      run_e2e:
        description: 'True to run e2e'
        required: true
        default: false
        type: boolean
      create_beta_package:
        description: 'True to create beta package'
        required: true
        default: false
        type: boolean
      package_version_name:
        required: false
        type: string
      package_version_number:
        required: false
        type: string

jobs:
  test:
    runs-on: ubuntu-latest
    outputs:
      scratch-username: ${{ steps.define-scratch-username.outputs.scratch-username }}
    steps:
    - name: checkout
      uses: actions/checkout@v3

    - name: setup salesforce cli
      uses: ./.github/actions/setup-salesforce-cli

    - name: install sfdx-lwc-jest by npm
      run: |
        npm install
    
    - name: run jest
      run: |
        sf force lightning lwc test run

    - name: authorize devhub org
      uses: ./.github/actions/authorize-org
      with:
        encoded_private_key_content: ${{ secrets.devhub_org_encoded_private_key_content }}
        encode_raw_key: ${{ secrets.devhub_org_encode_raw_key }}
        encode_iv: ${{ secrets.devhub_org_encode_iv }}
        client_id: ${{ secrets.devhub_org_client_id }}
        username: ${{ secrets.devhub_org_username }}
        alias: devhub
        is-devhub: true
        set-default: true
    
    - name: create scratch org
      if: ${{ inputs.scratch_username == '' }}
      run: |
        sf org create scratch --definition-file config/project-scratch-def.json --set-default --alias scratch --json

    - name: authorize scratch org
      if: ${{ inputs.scratch_username != '' }}
      uses: ./.github/actions/authorize-org
      with:
        encoded_private_key_content: ${{ secrets.devhub_org_encoded_private_key_content }}
        encode_raw_key: ${{ secrets.devhub_org_encode_raw_key }}
        encode_iv: ${{ secrets.devhub_org_encode_iv }}
        client_id: ${{ secrets.devhub_org_client_id }}
        username: ${{ inputs.scratch_username }}
        alias: scratch
        is-scratch: true
        set-default: true

    - name: define scratch username
      id: define-scratch-username
      run: |
        declare scratch_username=$(sf org display -o scratch --json | jq -r '.result.username')
        echo "scratch-username=${scratch_username}" >> "$GITHUB_OUTPUT"

    - name: deploy to scratch org
      run: sf project deploy start --ignore-conflicts

    - name: run apex test 
      id: run-apex-test
      run: |
        apex_test_results_dir=${RUNNER_TEMP}/build/apex-test-results
        sf apex run test --code-coverage --synchronous --result-format json --output-dir ${apex_test_results_dir}

        echo "apex_test_results_dir=${apex_test_results_dir}" >> "$GITHUB_OUTPUT"

    - name: archive apex test results
      id: archive-apex-test-results
      run: |
        declare apex_test_results_dir=${{ steps.run-apex-test.outputs.apex_test_results_dir }}
        declare archive_file=${RUNNER_TEMP}/$(basename ${apex_test_results_dir}).zip

        cd $(dirname ${apex_test_results_dir})
        zip -r ${archive_file} $(basename ${apex_test_results_dir})

        echo "archive_file=${archive_file}" >> "$GITHUB_OUTPUT"

    - name: upload apex test results
      uses: actions/upload-artifact@v3
      with:
        name: apex-test-results
        path: ${{ steps.archive-apex-test-results.outputs.archive_file }}

  e2e:
    needs: test
    if: ${{ inputs.run_e2e }}
    runs-on: ubuntu-latest
    env:
      scratch_username: ${{needs.test.outputs.scratch-username}}
    steps:
    - name: Setup japanese fonts
      run: |
        sudo apt-get -y update
        sudo apt-get -y install fonts-ipafont fonts-ipaexfont
        sudo fc-cache -fv
        sudo fc-list | grep -i ipa

    - name: checkout
      uses: actions/checkout@v3

    - name: setup salesforce cli
      uses: ./.github/actions/setup-salesforce-cli

    - name: setup java
      uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: '17'
        cache: 'maven'

    - name: setup gauge
      run: |
        curl -SsL https://downloads.gauge.org/stable | sh
        gauge --version

        gauge install java
        gauge install html-report
        gauge install screenshot
        gauge --version

    - name: authorize devhub org
      uses: ./.github/actions/authorize-org
      with:
        encoded_private_key_content: ${{ secrets.devhub_org_encoded_private_key_content }}
        encode_raw_key: ${{ secrets.devhub_org_encode_raw_key }}
        encode_iv: ${{ secrets.devhub_org_encode_iv }}
        client_id: ${{ secrets.devhub_org_client_id }}
        username: ${{ secrets.devhub_org_username }}
        alias: devhub
        is-devhub: true
        set-default: true

    - name: authorize scratch org
      uses: ./.github/actions/authorize-org
      with:
        encoded_private_key_content: ${{ secrets.devhub_org_encoded_private_key_content }}
        encode_raw_key: ${{ secrets.devhub_org_encode_raw_key }}
        encode_iv: ${{ secrets.devhub_org_encode_iv }}
        client_id: ${{ secrets.devhub_org_client_id }}
        username: ${scratch_username}
        alias: scratch
        is-scratch: true
        set-default: true

    - name: generate password for test admin user
      run: |
        sf org generate password -o scratch

    - name: configure .env-local
      run: |
        cd e2e
        ./script/generate-env.sh scratch > ./.env-local
        cat ./.env-local

    - name: compile e2e
      run: |
        cd e2e
        ./mvnw clean test-compile

    - name: run e2e
      run: |
        cd e2e
        ./mvnw gauge:execute

    - name: archive e2e reports
      if: ${{ always() }}
      id: archive-e2e-reports
      run: |
        declare archive_file=${RUNNER_TEMP}/e2e-reports.zip

        cd e2e
        zip -r ${archive_file} reports

        echo "archive_file=${archive_file}" >> "$GITHUB_OUTPUT"

    - name: upload e2e reports
      if: ${{ always() }}
      uses: actions/upload-artifact@v3
      with:
        name: e2e-reports
        path: ${{ steps.archive-e2e-reports.outputs.archive_file }}

  create-beta-package:
    needs: [test, e2e]
    if: ${{ inputs.create_beta_package }}
    runs-on: ubuntu-latest
    steps:
    - name: checkout
      uses: actions/checkout@v3

    - name: setup salesforce cli
      uses: ./.github/actions/setup-salesforce-cli

    - name: convert source to metadata
      run: |
        sf project convert source --output-dir metadata --json
        ls -lR metadata
        cat metadata/package.xml

    - name: authorize package org
      uses: ./.github/actions/authorize-org
      with:
        encoded_private_key_content: ${{ secrets.package_org_encoded_private_key_content }}
        encode_raw_key: ${{ secrets.package_org_encode_raw_key }}
        encode_iv: ${{ secrets.package_org_encode_iv }}
        client_id: ${{ secrets.package_org_client_id }}
        username: ${{ secrets.package_org_username }}
        alias: package
        set-default: true

    - name: deploy metadata to package org
      run: |
        sf project deploy start --manifest metadata/package.xml

    - name: create beta package version
      uses: ./.github/actions/create-package-version
      with:
        metadata_package_id: ${{ secrets.package_metadata_package_id }}
        version_name: ${{ inputs.package_version_name }}
        version_number: ${{ inputs.package_version_number }}
        alias: package