name: Demo workflow

on:
  workflow_dispatch:
    inputs:
      scratch_username:
        description: 'when input, connected to username for scratch'
        required: false
        type: string

jobs:
  demo:
    runs-on: ubuntu-latest
    steps:
    - name: checkout
      uses: actions/checkout@v3

    - name: setup salesforce cli
      uses: ./.github/actions/setup-salesforce-cli

    - name: authorize devhub org
      uses: ./.github/actions/authorize-org
      with:
        encoded_private_key_content: ${{ secrets.devhub_org_encoded_private_key_content }}
        encode_raw_key: ${{ secrets.devhub_org_encode_raw_key }}
        encode_iv: ${{ secrets.devhub_org_encode_iv }}
        client_id: ${{ secrets.devhub_org_client_id }}
        username: ${{ secrets.devhub_org_username }}
        alias: devhub
        is-devhub: true
        set-default: true

    - name: authorize scratch org
      uses: ./.github/actions/authorize-org
      with:
        encoded_private_key_content: ${{ secrets.devhub_org_encoded_private_key_content }}
        encode_raw_key: ${{ secrets.devhub_org_encode_raw_key }}
        encode_iv: ${{ secrets.devhub_org_encode_iv }}
        client_id: ${{ secrets.devhub_org_client_id }}
        username: ${{ inputs.scratch_username }}
        alias: scratch
        is-scratch: true
        set-default: true

    - name: generate password for test admin user
      run: |
        sf org generate password -o scratch

    - name: set loginIpRange to standard profile
      uses: ./.github/actions/set-loginIpRanges-to-profile
      with:
        alias: scratch
        profile: Standard
        start-address: 0.0.0.0
        end-address: 255.255.255.255
