name: Demo workflow

on: workflow_dispatch

jobs:
  demo:
    runs-on: ubuntu-latest
    steps:
    - name: checkout
      uses: actions/checkout@v3

    - name: run demo
      run: |
        cd e2e
        sh ./script/demo.sh foo bar