name: Demo workflow

on:
  workflow_dispatch:
    inputs:
      scratch_username:
        description: 'when input, connected to username for scratch'
        required: false
        type: string
      package_version_name:
        required: false
        type: string
      package_version_number:
          required: false
          type: string
  
jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
    - name: checkout
      uses: actions/checkout@v3

    - id: foo
      uses: ./.github/actions/hello
      with:
        who-to-greet: 'John'

    - name: post hello
      run: |
        echo greet is ${{ steps.foo.outputs.greet }}

    - uses: ./.github/actions/setup-salesforce-cli

    - name: authorize devhub org
      uses: ./.github/actions/authorize-org
      with:
        encoded_private_key_content: ${{ secrets.devhub_org_encoded_private_key_content }}
        encode_raw_key: ${{ secrets.devhub_org_encode_raw_key }}
        encode_iv: ${{ secrets.devhub_org_encode_iv }}
        client_id: ${{ secrets.devhub_org_client_id }}
        username: ${{ secrets.devhub_org_username }}
        alias: devhub
        is-devhub: true
        set-default: true

    - name: authorize scratch org
      uses: ./.github/actions/authorize-org
      with:
        encoded_private_key_content: ${{ secrets.devhub_org_encoded_private_key_content }}
        encode_raw_key: ${{ secrets.devhub_org_encode_raw_key }}
        encode_iv: ${{ secrets.devhub_org_encode_iv }}
        client_id: ${{ secrets.devhub_org_client_id }}
        username: ${{ inputs.scratch_username }}
        alias: scratch
        is-scratch: true
        set-default: true
  
    - name: authorize package org
      uses: ./.github/actions/authorize-org
      with:
        encoded_private_key_content: ${{ secrets.package_org_encoded_private_key_content }}
        encode_raw_key: ${{ secrets.package_org_encode_raw_key }}
        encode_iv: ${{ secrets.package_org_encode_iv }}
        client_id: ${{ secrets.package_org_client_id }}
        username: ${{ secrets.package_org_username }}
        alias: package
  
    - name: convert source to metadata
      run: |
        sf project convert source --output-dir metadata --json
        ls -lR metadata
        cat metadata/package.xml
  
    - name: deploy metadata to package org
      run: |
        sf project deploy start --manifest metadata/package.xml -o package

    - name: create beta package version
      uses: ./.github/actions/create-package-version
      with:
        metadata_package_id: ${{ secrets.package_metadata_package_id }}
        version_name: ${{ inputs.package_version_name }}
        version_number: ${{ inputs.package_version_number }}
        alias: package